// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClw9Zqxwuz0QMfDWWQJ3HFMXeXr17mu-I',
    appId: '1:449867052101:web:ebc870dc266ce71ac29f2c',
    messagingSenderId: '449867052101',
    projectId: 'baraja-coffee',
    authDomain: 'baraja-coffee.firebaseapp.com',
    databaseURL: 'https://baraja-coffee-default-rtdb.firebaseio.com',
    storageBucket: 'baraja-coffee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lCdO8OnEJikK20UDhf8qWS-JlNSGaIo',
    appId: '1:449867052101:android:d5b9ba5d52242965c29f2c',
    messagingSenderId: '449867052101',
    projectId: 'baraja-coffee',
    databaseURL: 'https://baraja-coffee-default-rtdb.firebaseio.com',
    storageBucket: 'baraja-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHR0hWXrFq3fwEmFPRAGaTRnmOgvtJmC4',
    appId: '1:449867052101:ios:d6d17dd3a201cab6c29f2c',
    messagingSenderId: '449867052101',
    projectId: 'baraja-coffee',
    databaseURL: 'https://baraja-coffee-default-rtdb.firebaseio.com',
    storageBucket: 'baraja-coffee.firebasestorage.app',
    androidClientId: '449867052101-9fnv2bibrbpvgvfvoblksiemtklbk78j.apps.googleusercontent.com',
    iosClientId: '449867052101-rpfqr9etk2bgcmdvk5kpa8mco25m9sam.apps.googleusercontent.com',
    iosBundleId: 'com.testinggorouter.testingGoRouter',
  );
}
