// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kasirbaraja/models/addon.model.dart';
import 'package:kasirbaraja/models/addon_option.model.dart';
import 'package:kasirbaraja/models/bluetooth_printer.model.dart';
import 'package:kasirbaraja/models/cashier.model.dart';
import 'package:kasirbaraja/models/menu_category.model.dart';
import 'package:kasirbaraja/models/menu_item.model.dart';
import 'package:kasirbaraja/models/menu_subcategory.model.dart';
import 'package:kasirbaraja/models/order_detail.model.dart';
import 'package:kasirbaraja/models/order_item.model.dart';
import 'package:kasirbaraja/models/tax_and_service.model.dart';
import 'package:kasirbaraja/models/topping.model.dart';
import 'package:kasirbaraja/models/user.model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
