// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kasirbaraja/models/addon.model.dart';
import 'package:kasirbaraja/models/addon_option.model.dart';
import 'package:kasirbaraja/models/affected_item.model.dart';
import 'package:kasirbaraja/models/applied_promos.model.dart';
import 'package:kasirbaraja/models/auto_promo.model.dart';
import 'package:kasirbaraja/models/bluetooth_printer.model.dart';
import 'package:kasirbaraja/models/cashier.model.dart';
import 'package:kasirbaraja/models/custom_amount_items.model.dart';
import 'package:kasirbaraja/models/custom_discount.model.dart';
import 'package:kasirbaraja/models/device.model.dart';
import 'package:kasirbaraja/models/discount.model.dart';
import 'package:kasirbaraja/models/edit_order_item.model.dart';
import 'package:kasirbaraja/models/event.model.dart';
import 'package:kasirbaraja/models/free_item.model.dart';
import 'package:kasirbaraja/models/menu_category.model.dart';
import 'package:kasirbaraja/models/menu_item.model.dart';
import 'package:kasirbaraja/models/menu_stock.model.dart';
import 'package:kasirbaraja/models/menu_subcategory.model.dart';
import 'package:kasirbaraja/models/order_detail.model.dart';
import 'package:kasirbaraja/models/order_item.model.dart';
import 'package:kasirbaraja/models/outlet_info.model.dart';
import 'package:kasirbaraja/models/payments/payment.model.dart';
import 'package:kasirbaraja/models/payments/payment_action.model.dart';
import 'package:kasirbaraja/models/payments/payment_method.model.dart';
import 'package:kasirbaraja/models/payments/payment_type.model.dart';
import 'package:kasirbaraja/models/payments/va_number.model.dart';
import 'package:kasirbaraja/models/promo_group.model.dart';
import 'package:kasirbaraja/models/tax_and_service.model.dart';
import 'package:kasirbaraja/models/tax_service_detail.model.dart';
import 'package:kasirbaraja/models/topping.model.dart';
import 'package:kasirbaraja/models/user.model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActiveHoursModelAdapter());
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(AffectedItemModelAdapter());
    registerAdapter(AppliedPromosModelAdapter());
    registerAdapter(AutoPromoModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(BundleProductModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(CustomAmountItemsModelAdapter());
    registerAdapter(CustomDiscountModelAdapter());
    registerAdapter(DeviceModelAdapter());
    registerAdapter(DiscountModelAdapter());
    registerAdapter(EditOrderItemModelAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(FreeItemModelAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuStockModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(OutletInfoModelAdapter());
    registerAdapter(OutletModelAdapter());
    registerAdapter(PaymentActionModelAdapter());
    registerAdapter(PaymentMethodModelAdapter());
    registerAdapter(PaymentModelAdapter());
    registerAdapter(PaymentTypeModelAdapter());
    registerAdapter(PromoConditionsModelAdapter());
    registerAdapter(PromoGroupLineModelAdapter());
    registerAdapter(PromoGroupModelAdapter());
    registerAdapter(PromoProductModelAdapter());
    registerAdapter(ScheduleModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(TaxServiceDetailModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VANumberModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActiveHoursModelAdapter());
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(AffectedItemModelAdapter());
    registerAdapter(AppliedPromosModelAdapter());
    registerAdapter(AutoPromoModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(BundleProductModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(CustomAmountItemsModelAdapter());
    registerAdapter(CustomDiscountModelAdapter());
    registerAdapter(DeviceModelAdapter());
    registerAdapter(DiscountModelAdapter());
    registerAdapter(EditOrderItemModelAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(FreeItemModelAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuStockModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(OutletInfoModelAdapter());
    registerAdapter(OutletModelAdapter());
    registerAdapter(PaymentActionModelAdapter());
    registerAdapter(PaymentMethodModelAdapter());
    registerAdapter(PaymentModelAdapter());
    registerAdapter(PaymentTypeModelAdapter());
    registerAdapter(PromoConditionsModelAdapter());
    registerAdapter(PromoGroupLineModelAdapter());
    registerAdapter(PromoGroupModelAdapter());
    registerAdapter(PromoProductModelAdapter());
    registerAdapter(ScheduleModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(TaxServiceDetailModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VANumberModelAdapter());
  }
}
