// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kasirbaraja/models/addon.model.dart';
import 'package:kasirbaraja/models/addon_option.model.dart';
import 'package:kasirbaraja/models/bluetooth_printer.model.dart';
import 'package:kasirbaraja/models/cashier.model.dart';
import 'package:kasirbaraja/models/device.model.dart';
import 'package:kasirbaraja/models/discount.model.dart';
import 'package:kasirbaraja/models/event.model.dart';
import 'package:kasirbaraja/models/menu_category.model.dart';
import 'package:kasirbaraja/models/menu_item.model.dart';
import 'package:kasirbaraja/models/menu_subcategory.model.dart';
import 'package:kasirbaraja/models/order_detail.model.dart';
import 'package:kasirbaraja/models/order_item.model.dart';
import 'package:kasirbaraja/models/outlet_info.model.dart';
import 'package:kasirbaraja/models/payments/payment.model.dart';
import 'package:kasirbaraja/models/payments/payment_action.model.dart';
import 'package:kasirbaraja/models/payments/payment_method.model.dart';
import 'package:kasirbaraja/models/payments/payment_type.model.dart';
import 'package:kasirbaraja/models/payments/va_number.model.dart';
import 'package:kasirbaraja/models/tax_and_service.model.dart';
import 'package:kasirbaraja/models/tax_service_detail.model.dart';
import 'package:kasirbaraja/models/topping.model.dart';
import 'package:kasirbaraja/models/user.model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(DeviceModelAdapter());
    registerAdapter(DiscountModelAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(OutletInfoModelAdapter());
    registerAdapter(PaymentActionModelAdapter());
    registerAdapter(PaymentMethodModelAdapter());
    registerAdapter(PaymentModelAdapter());
    registerAdapter(PaymentTypeModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(TaxServiceDetailModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VANumberModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddonModelAdapter());
    registerAdapter(AddonOptionModelAdapter());
    registerAdapter(BluetoothPrinterModelAdapter());
    registerAdapter(CashierModelAdapter());
    registerAdapter(DeviceModelAdapter());
    registerAdapter(DiscountModelAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(MenuCategoryModelAdapter());
    registerAdapter(MenuItemModelAdapter());
    registerAdapter(MenuSubCategoryModelAdapter());
    registerAdapter(OrderDetailModelAdapter());
    registerAdapter(OrderItemModelAdapter());
    registerAdapter(OutletInfoModelAdapter());
    registerAdapter(PaymentActionModelAdapter());
    registerAdapter(PaymentMethodModelAdapter());
    registerAdapter(PaymentModelAdapter());
    registerAdapter(PaymentTypeModelAdapter());
    registerAdapter(TaxAndServiceModelAdapter());
    registerAdapter(TaxServiceDetailModelAdapter());
    registerAdapter(ToppingModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VANumberModelAdapter());
  }
}
