version: '3.8'

services:
  app:
    container_name: barajacoffee-app
    image: barajacoffee/barajacoffee:latest
    ports:
      - "3000:3000" # Ganti sesuai port aplikasi Anda
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped
    networks:
      - baraja-net

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - baraja-net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup barajacoffee-app
    restart: unless-stopped
    networks:
      - baraja-net

volumes:
  redis-data:

networks:
  baraja-net:
    driver: bridge
