name: barajapos
description: "Baraja Pos"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  path_provider_android: 2.2.5
  hive_ce: ^2.10.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  hive_ce_flutter: ^2.1.0
  flutter_dotenv: ^5.2.1

assets:
  - .env

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_ce_generator: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - .env
