name: kasirbaraja
description: "Kasir Baraja."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  path_provider_android: 2.2.5
  hive_ce: ^2.10.1
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  hive_ce_flutter: ^2.1.0
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.0.0
  bcrypt: ^1.1.3
  collection: ^1.19.1
  json_annotation: ^4.9.0
  flutter_reactive_ble: ^5.4.0
  assorted_layout_widgets: ^11.0.0
  permission_handler: ^12.0.0+1
  flutter_thermal_printer: ^1.2.1+1
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  socket_io_client: ^3.1.2

assets:
  - .env

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  build_runner: ^2.4.6
  hive_ce_generator: ^1.8.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - .env
