name: Docker Build and Push

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/barajahub"
          docker build -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME:latest"
